name: doc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  badges: ^3.1.2
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.6
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_messaging: ^15.2.5
  firebase_storage: ^11.5.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  image_picker: ^1.0.7
  intl: ^0.20.2
  lottie: ^3.3.1
  path: ^1.8.3
  provider: ^6.1.4
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  shimmer_animation: ^2.2.2
  photo_view: ^0.14.0
  url_launcher: ^6.2.4
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/onboarding1.png
    - assets/promo_images/