// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6RBxqmaoYE-vn062jOW2vrAD1DARKOGE',
    appId: '1:558519944138:web:a030f2b76a3ce7c20a8533',
    messagingSenderId: '558519944138',
    projectId: 'doc1-a1d62',
    authDomain: 'doc1-a1d62.firebaseapp.com',
    storageBucket: 'doc1-a1d62.firebasestorage.app',
    measurementId: 'G-165VY3JQL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqlJiW8_wQbIkWEDy5cXUPtRPwNYeP0Kw',
    appId: '1:558519944138:android:d495e66b3809fab20a8533',
    messagingSenderId: '558519944138',
    projectId: 'doc1-a1d62',
    storageBucket: 'doc1-a1d62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7qb_At5quuyX3-U9CP5b7Ic8koI6vlYM',
    appId: '1:558519944138:ios:968d8b7354f857df0a8533',
    messagingSenderId: '558519944138',
    projectId: 'doc1-a1d62',
    storageBucket: 'doc1-a1d62.firebasestorage.app',
    iosBundleId: 'com.example.doc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7qb_At5quuyX3-U9CP5b7Ic8koI6vlYM',
    appId: '1:558519944138:ios:968d8b7354f857df0a8533',
    messagingSenderId: '558519944138',
    projectId: 'doc1-a1d62',
    storageBucket: 'doc1-a1d62.firebasestorage.app',
    iosBundleId: 'com.example.doc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6RBxqmaoYE-vn062jOW2vrAD1DARKOGE',
    appId: '1:558519944138:web:337df9315626249e0a8533',
    messagingSenderId: '558519944138',
    projectId: 'doc1-a1d62',
    authDomain: 'doc1-a1d62.firebaseapp.com',
    storageBucket: 'doc1-a1d62.firebasestorage.app',
    measurementId: 'G-TNJRD53G6D',
  );
}
